import { Product, Collection } from "./types";

const CDN = "https://cdn.shopify.com/s/files/1/0763/3672/6242/files";

export const products: Product[] = [
  {
    id: "1",
    name: "Adler – Beige & Brown Hand-Knotted Wool & Silk",
    handle: "adler-beige-brown-hand-knotted-wool-silk-carpet",
    price: 32500,
    compareAtPrice: 45500,
    images: [`${CDN}/Adler7.jpg`, `${CDN}/Adler.png`, `${CDN}/IMG_2408.jpg`, `${CDN}/IMG_2224.png`],
    category: "hand-knotted",
    material: "Wool & Silk",
    sizes: ["4×6 ft", "5×8 ft", "6×9 ft", "8×10 ft"],
    colors: ["Beige", "Brown"],
    description: "A masterwork of artisan hands, the Adler carpet blends premium New Zealand wool with lustrous silk to create a surface that shifts and shimmers with natural light. Each knot is tied individually by skilled weavers, producing a density and richness that machine-made carpets simply cannot replicate.",
    features: ["Hand-knotted construction", "New Zealand wool + silk blend", "200 knots per square inch", "Naturally dye-resistant", "Reversible pile"],
    care: "Vacuum regularly without beater bar. Spot-clean with cold water. Professional clean recommended annually.",
    inStock: true,
    isBestseller: true,
  },
  {
    id: "2",
    name: "Bell – Beige & Rust Hand-Knotted Wool & Silk",
    handle: "bell-beige-rust-hand-knotted-wool-silk-carpet",
    price: 32500,
    compareAtPrice: 45500,
    images: [`${CDN}/Bell1.jpg`, `${CDN}/IMG_2273.jpg`, `${CDN}/IMG_2271.jpg`, `${CDN}/IMG_2279.jpg`, `${CDN}/IMG_2229.png`],
    category: "hand-knotted",
    material: "Wool & Silk",
    sizes: ["4×6 ft", "5×8 ft", "6×9 ft", "8×10 ft"],
    colors: ["Beige", "Rust"],
    description: "The Bell carpet carries a warm rust palette inspired by sun-baked earth. Its intricate medallion motif is hand-knotted by master craftsmen from Agra, where the tradition of carpet weaving stretches back five centuries.",
    features: ["Hand-knotted in Agra", "Wool & silk blend", "Traditional medallion motif", "Natural dyes", "Heirloom quality"],
    care: "Vacuum gently. Rotate every 6 months for even wear. Avoid direct sunlight.",
    inStock: true,
  },
  {
    id: "3",
    name: "Brilliance – Beige & Dark Brown Hand-Knotted Wool & Silk",
    handle: "brilliance-beige-dark-brown-hand-knotted-wool-silk-carpet",
    price: 32500,
    compareAtPrice: 45500,
    images: [`${CDN}/Brilliance.jpg`, `${CDN}/brilliance.png`, `${CDN}/IMG_2354.jpg`, `${CDN}/IMG_2338.jpg`, `${CDN}/IMG_2341.jpg`],
    category: "hand-knotted",
    material: "Wool & Silk",
    sizes: ["4×6 ft", "5×8 ft", "6×9 ft"],
    colors: ["Beige", "Dark Brown"],
    description: "Understated yet deeply intricate, Brilliance brings quiet grandeur to any space. The contrast of deep espresso against warm beige creates a timeless elegance suited to both contemporary and classical interiors.",
    features: ["Hand-knotted construction", "Wool & silk blend", "Tightly knotted for fine detail", "Colourfast natural dyes", "Certificate of authenticity included"],
    care: "Professional cleaning recommended. Vacuum with low suction. Avoid moisture.",
    inStock: true,
    isBestseller: true,
  },
  {
    id: "4",
    name: "Brilliance – Green & Rose Gold Hand-Knotted Wool & Silk",
    handle: "brilliance-green-rose-gold-hand-knotted-wool-silk-carpet",
    price: 74500,
    compareAtPrice: 105000,
    images: [`${CDN}/IMG_0386_1.jpg`, `${CDN}/Brilliance_1.jpg`, `${CDN}/IMG_0388_1.jpg`, `${CDN}/IMG_0390_1.jpg`],
    category: "hand-knotted",
    material: "Wool & Silk",
    sizes: ["6×9 ft", "8×10 ft", "9×12 ft"],
    colors: ["Green", "Rose Gold"],
    description: "A statement piece for those who refuse to compromise. The Green & Rose Gold Brilliance is woven with silk threads that catch the light like jewels. Reserved for the finest rooms.",
    features: ["Museum-grade craftsmanship", "Silk pile on wool foundation", "300 knots per square inch", "Unique colourway", "Signed by the master weaver"],
    care: "Professional cleaning only. Do not vacuum the silk surface directly.",
    inStock: true,
    isNew: true,
  },
  {
    id: "5",
    name: "Bronte – Multicolor Hand-Tufted Wool",
    handle: "bronte-multicolor-hand-tufted-wool-carpet",
    price: 8500,
    compareAtPrice: 17500,
    images: [`${CDN}/Bronte_1.png`, `${CDN}/Bronte_5.jpg`, `${CDN}/Bronte_2.jpg`, `${CDN}/Bronte_3.jpg`],
    category: "hand-tufted",
    material: "Wool",
    sizes: ["4×6 ft", "5×8 ft", "6×9 ft"],
    colors: ["Multicolor"],
    description: "The Bronte brings an artistic multicolor pattern to your space with modern abstract detailing. Its dense wool pile creates a plush underfoot experience that makes every step a pleasure.",
    features: ["Hand-tufted wool construction", "Dense pile for comfort", "Colour-stable dyes", "Non-shedding after first week", "Anti-slip backing available"],
    care: "Vacuum weekly. Machine washable (4×6 ft only). Spot clean larger sizes.",
    inStock: true,
  },
  {
    id: "6",
    name: "Blocks Blue – Blue & Teal Hand-Tufted Wool & Silk",
    handle: "blocks-red-red-maroon-hand-tufted-wool-silk-carpet-copy",
    price: 7850,
    compareAtPrice: 14500,
    images: [`${CDN}/blocksblue_1_1.png`, `${CDN}/blocksblue_4_1.jpg`, `${CDN}/blocksblue_2_1.jpg`],
    category: "hand-tufted",
    material: "Wool & Silk",
    sizes: ["4×6 ft", "5×8 ft", "6×9 ft"],
    colors: ["Blue", "Teal"],
    description: "A bold geometric statement in cool blues and teal, the Blocks carpet brings modern art sensibility to floor coverings. The interplay of wool and silk creates a subtle sheen across the geometric pattern.",
    features: ["Hand-tufted wool & silk", "Geometric block pattern", "Silk accent threads", "Contemporary design", "Suitable for high-traffic areas"],
    care: "Vacuum without beater bar. Rotate seasonally for even wear.",
    inStock: true,
  },
  {
    id: "7",
    name: "Blocks Red – Red & Maroon Hand-Tufted Wool & Silk",
    handle: "blocks-red-wool-silk-carpet",
    price: 7850,
    compareAtPrice: 14500,
    images: [`${CDN}/BlocksRed.jpg`, `${CDN}/blocks_red_1_11c80262-5f80-488c-a522-49e88c0f6c13.png`, `${CDN}/blocks_red_3_1.jpg`, `${CDN}/blocks_red_4_1.jpg`],
    category: "hand-tufted",
    material: "Wool & Silk",
    sizes: ["4×6 ft", "5×8 ft", "6×9 ft"],
    colors: ["Red", "Maroon"],
    description: "Deep crimson meets rich maroon in this bold geometric carpet. The Blocks Red makes a confident statement in dining rooms and study spaces where character is prized.",
    features: ["Hand-tufted construction", "Wool & silk blend", "Rich red palette", "Geometric pattern", "Durable pile"],
    care: "Vacuum weekly. Avoid steam cleaning. Spot treat immediately.",
    inStock: true,
  },
  {
    id: "8",
    name: "Downes – Multicolor Hand-Tufted Wool & Silk",
    handle: "blocks-blue-blue-teal-hand-tufted-wool-silk-carpet-copy",
    price: 7850,
    compareAtPrice: 14500,
    images: [`${CDN}/Downes_1_1.png`, `${CDN}/Downes.jpg`, `${CDN}/Downes_5_1.jpg`, `${CDN}/Downes_3_1.jpg`],
    category: "hand-tufted",
    material: "Wool & Silk",
    sizes: ["4×6 ft", "5×8 ft", "6×9 ft"],
    colors: ["Multicolor"],
    description: "Downes celebrates the beauty of natural hues in an abstract, painterly composition. Woven with both wool and silk, the carpet's surface offers gentle variation in sheen that brings the design to life.",
    features: ["Hand-tufted wool & silk", "Abstract painterly design", "Silk adds visual depth", "Artist-designed pattern", "Limited run"],
    care: "Dry clean recommended. Vacuum with low suction.",
    inStock: true,
    isNew: true,
  },
  {
    id: "9",
    name: "Dutch – Multicolor Hand-Knotted Wool & Silk",
    handle: "brilliance-beige-dark-brown-hand-knotted-wool-silk-carpet-copy",
    price: 34500,
    compareAtPrice: 48500,
    images: [`${CDN}/Dutch.jpg`, `${CDN}/IMG_2286.jpg`, `${CDN}/IMG_2294.jpg`, `${CDN}/IMG_2290.jpg`, `${CDN}/IMG_2232.png`],
    category: "hand-knotted",
    material: "Wool & Silk",
    sizes: ["5×8 ft", "6×9 ft", "8×10 ft"],
    colors: ["Multicolor"],
    description: "Named for the rich Flemish tradition of decorative arts, the Dutch carpet is an exercise in restrained opulence. Its intricate border and field design draws on centuries of weaving heritage.",
    features: ["Fine hand-knotted construction", "Heritage design", "Wool & silk blend", "Intricate border detail", "Investment quality"],
    care: "Professional cleaning only. Rotate twice yearly.",
    inStock: true,
    isBestseller: true,
  },
  {
    id: "10",
    name: "Embrace – Cream & Black Hand-Tufted",
    handle: "embrace-cream-black-hand-tufted-carpet",
    price: 12500,
    compareAtPrice: 17500,
    images: [`${CDN}/embrace_1.png`, `${CDN}/embrace5_1.jpg`, `${CDN}/embrace4_1.jpg`, `${CDN}/embrace1_1.png`],
    category: "hand-tufted",
    material: "Wool",
    sizes: ["4×6 ft", "5×8 ft", "6×9 ft"],
    colors: ["Cream", "Black"],
    description: "The Embrace is built on a classic contrast — cream and black — rendered in a modern organic pattern. It pairs effortlessly with both minimal and maximalist interiors.",
    features: ["Hand-tufted wool", "High-contrast colourway", "Modern organic pattern", "Deep pile for comfort", "Versatile styling"],
    care: "Vacuum regularly. Spot clean with mild soap and cold water.",
    inStock: true,
  },
  {
    id: "11",
    name: "Escuella – Multicolor Hand-Tufted Wool",
    handle: "escuella-multicolor-hand-tufted-wool-silk-carpet",
    price: 8500,
    compareAtPrice: 17500,
    images: [`${CDN}/Escuella_1.png`, `${CDN}/Escuella.jpg`, `${CDN}/Escuella_4_1.jpg`, `${CDN}/Escuella_3_1.jpg`],
    category: "hand-tufted",
    material: "Wool",
    sizes: ["4×6 ft", "5×8 ft", "6×9 ft"],
    colors: ["Multicolor"],
    description: "Escuella draws on Moorish geometric traditions, reinterpreted for the modern home. Its rich multicolor palette creates warmth and visual complexity in equal measure.",
    features: ["Hand-tufted wool", "Moorish-inspired geometry", "Rich colour palette", "Dense pile weight", "Easy care"],
    care: "Vacuum weekly. Rotate every 6 months.",
    inStock: true,
  },
  {
    id: "12",
    name: "Gaskill – Multicolor Hand-Tufted Wool",
    handle: "summers-multicolor-hand-tufted-wool-carpet-copy",
    price: 8500,
    compareAtPrice: 17500,
    images: [`${CDN}/Gaskill_1.png`, `${CDN}/Gaskill_5.jpg`, `${CDN}/Gaskill_4.jpg`],
    category: "hand-tufted",
    material: "Wool",
    sizes: ["4×6 ft", "5×8 ft", "6×9 ft"],
    colors: ["Multicolor"],
    description: "Gaskill is a celebration of colour and craft. Its vibrant multicolour field is hand-tufted into a dense wool pile, creating a carpet that anchors a room with joyful energy.",
    features: ["Hand-tufted wool", "Vibrant multicolor design", "High pile density", "Colour-stable dyes", "Ideal for living rooms"],
    care: "Vacuum without beater bar. Spot clean as needed.",
    inStock: true,
  },
  {
    id: "13",
    name: "Ghaba – Cream & Blue Hand-Tufted",
    handle: "ghaba-cream-blue-hand-tufted-carpet",
    price: 12500,
    compareAtPrice: 17500,
    images: [`${CDN}/ghaba_1.png`, `${CDN}/ghaba5_1.jpg`, `${CDN}/ghaba4_1.jpg`, `${CDN}/ghaba1_1.png`],
    category: "hand-tufted",
    material: "Wool",
    sizes: ["4×6 ft", "5×8 ft", "6×9 ft"],
    colors: ["Cream", "Blue"],
    description: "The Ghaba pairs an ivory ground with deep blue detailing in a pattern that recalls indigo-dyed textiles of the Nile Delta. Cool, serene, and timelessly elegant.",
    features: ["Hand-tufted wool", "Indigo-inspired palette", "Fine motif detail", "Soft underfoot", "Classic design"],
    care: "Vacuum regularly. Professional cleaning recommended annually.",
    inStock: false,
  },
  {
    id: "14",
    name: "Grove – Multicolor Handloom Wool",
    handle: "grove-multicolor-handloom-wool-carpet",
    price: 17500,
    compareAtPrice: 28500,
    images: [`${CDN}/bdc5a51a-7a2c-4f4c-9eb1-6db76f95934e.jpg`, `${CDN}/IMG_0714_1.jpg`, `${CDN}/grove_1_1.jpg`],
    category: "handloom",
    material: "Wool",
    sizes: ["5×8 ft", "6×9 ft", "8×10 ft"],
    colors: ["Multicolor"],
    description: "Grove celebrates the meditative rhythm of handloom weaving. Each thread is placed by hand on a traditional loom, creating subtle texture variation that no machine can imitate.",
    features: ["Handloom woven", "100% natural wool", "Textural surface variation", "Traditional technique", "Eco-friendly dyes"],
    care: "Dry clean recommended. Vacuum on low.",
    inStock: true,
    isNew: true,
  },
  {
    id: "15",
    name: "Harb – Beige Hand-Tufted Wool",
    handle: "harb-beige-hand-tufted-wool-carpet",
    price: 17500,
    compareAtPrice: 27500,
    images: [`${CDN}/harb1_1.png`, `${CDN}/harb3.jpg`, `${CDN}/harb2_1.jpg`],
    category: "hand-tufted",
    material: "Wool",
    sizes: ["4×6 ft", "5×8 ft", "6×9 ft"],
    colors: ["Beige"],
    description: "Harb is the master of neutrals. Its warm beige tones and subtle surface texture make it the perfect foundation carpet — one that brings warmth without demanding attention.",
    features: ["Hand-tufted wool", "Tone-on-tone texture", "Neutral palette", "High pile for comfort", "Works with any interior style"],
    care: "Vacuum weekly. Spot clean. Professional care annually.",
    inStock: true,
    isBestseller: true,
  },
  {
    id: "16",
    name: "Harem – Green Hand-Knotted Wool",
    handle: "harem-green-hand-knotted-wool-carpet",
    price: 8200,
    compareAtPrice: 12500,
    images: [`${CDN}/ChatGPTImageAug5_2025_02_50_01PM_1.png`, `${CDN}/IMG_0058_1.jpg`, `${CDN}/IMG_0057_1.jpg`, `${CDN}/IMG_0061_1.jpg`],
    category: "hand-knotted",
    material: "Wool",
    sizes: ["4×6 ft", "5×8 ft", "6×9 ft"],
    colors: ["Green"],
    description: "Deep jewel-green rendered in intricate hand-knotted wool — the Harem brings the lush abundance of a garden indoors. Its dense construction and rich colour will deepen beautifully with age.",
    features: ["Hand-knotted wool", "Jewel green colourway", "Persian-inspired motifs", "Long-wearing construction", "Ages beautifully"],
    care: "Vacuum on low. Rotate every 6 months. Avoid direct sunlight to preserve colour.",
    inStock: true,
  },
  {
    id: "17",
    name: "Harf – Black Hand-Tufted",
    handle: "harf-black-hand-tufted-carpet",
    price: 12500,
    compareAtPrice: 17500,
    images: [`${CDN}/Harf_1.png`, `${CDN}/harf5_1.jpg`, `${CDN}/harf2_1.jpg`],
    category: "hand-tufted",
    material: "Wool",
    sizes: ["4×6 ft", "5×8 ft", "6×9 ft"],
    colors: ["Black"],
    description: "Harf proves that black is anything but absent. Its deep monochrome field holds a subtle woven pattern that reveals itself only at close inspection — a carpet for those who appreciate quiet sophistication.",
    features: ["Hand-tufted wool", "Tonal black on black pattern", "Dense pile", "Statement colourway", "Low maintenance"],
    care: "Vacuum regularly. Hides dirt well. Spot clean as needed.",
    inStock: true,
  },
  {
    id: "18",
    name: "Arf – Multicolor Wool Dhurrie",
    handle: "arf-multicolor-wool-dhurrie-carpet",
    price: 7499,
    compareAtPrice: 10499,
    images: [`${CDN}/arf1.jpg`, `${CDN}/arf4.jpg`, `${CDN}/arf2.jpg`, `${CDN}/arf3.png`],
    category: "dhurrie",
    material: "Wool",
    sizes: ["4×6 ft", "5×8 ft", "6×9 ft"],
    colors: ["Multicolor"],
    description: "Arf is a celebration of the flatwoven dhurrie tradition — lightweight, reversible, and bold. Its graphic multicolor pattern draws on the kilim heritage of North India.",
    features: ["Flatwoven dhurrie", "100% wool", "Fully reversible", "Lightweight", "Traditional kilim patterns"],
    care: "Machine washable (smaller sizes). Shake out dust regularly.",
    inStock: true,
  },
  {
    id: "19",
    name: "Cuhl – Multicolor Wool Dhurrie",
    handle: "cuhl-multicolor-wool-dhurrie-carpet",
    price: 7499,
    compareAtPrice: 10499,
    images: [`${CDN}/cuhl1.jpg`, `${CDN}/cuhl3.jpg`, `${CDN}/cuhl2.jpg`, `${CDN}/cuhl4.jpg`],
    category: "dhurrie",
    material: "Wool",
    sizes: ["4×6 ft", "5×8 ft", "6×9 ft"],
    colors: ["Multicolor"],
    description: "The Cuhl dhurrie brings vivid colour and graphic precision in a flatwoven format. Light enough for summer use, beautiful enough for year-round display.",
    features: ["Flatwoven wool dhurrie", "Graphic pattern", "Reversible", "Summer-friendly weight", "Vibrant colourway"],
    care: "Hand wash or machine wash on gentle. Air dry flat.",
    inStock: true,
  },
  {
    id: "20",
    name: "Fusion – Grey Handloom Silk",
    handle: "fusion-grey-handloom-silk-carpet",
    price: 6500,
    compareAtPrice: 8450,
    images: [`${CDN}/mosaic1.png`, `${CDN}/Mosaic_Grey_2.jpg`, `${CDN}/Mosaic_Grey_3.jpg`],
    category: "handloom",
    material: "Silk",
    sizes: ["4×6 ft", "5×8 ft", "6×9 ft"],
    colors: ["Grey"],
    description: "Fusion is handloom-woven in pure silk, producing a surface of extraordinary luminosity. Its cool grey tones shift from silver to charcoal depending on the light, making it a living artwork for the floor.",
    features: ["100% pure silk", "Handloom woven", "Light-reactive surface", "Ultra-fine weave", "Exquisite drape"],
    care: "Professional dry clean only. Never wet clean silk. Protect from sunlight.",
    inStock: true,
    isNew: true,
  },
];

export const collections: Collection[] = [
  {
    slug: "hand-knotted",
    name: "Hand-Knotted",
    description: "The pinnacle of carpet-making — each knot tied by hand over months of patient work.",
    image: `${CDN}/Adler7.jpg`,
    count: 7,
  },
  {
    slug: "hand-tufted",
    name: "Hand-Tufted",
    description: "Artisan-made with a tufting gun on a canvas backing for rich texture and depth.",
    image: `${CDN}/Bronte_1.png`,
    count: 10,
  },
  {
    slug: "dhurrie",
    name: "Dhurrie",
    description: "India's flatwoven tradition — lightweight, reversible, and boldly patterned.",
    image: `${CDN}/arf1.jpg`,
    count: 5,
  },
  {
    slug: "handloom",
    name: "Handloom",
    description: "Woven thread by thread on traditional looms for subtle texture and natural character.",
    image: `${CDN}/grove_1_1.jpg`,
    count: 3,
  },
];

export function getProductByHandle(handle: string): Product | undefined {
  return products.find((p) => p.handle === handle);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(price);
}

export const testimonials = [
  {
    name: "Priya Mehta",
    location: "Mumbai",
    text: "The Adler carpet transformed our living room completely. The quality is unlike anything we'd found at this price point — it looks like it belongs in a five-star hotel.",
    rating: 5,
    product: "Adler – Beige & Brown",
  },
  {
    name: "Rohan Kapoor",
    location: "Bengaluru",
    text: "Delivery was faster than expected and the carpet was even more beautiful in person. The colours are rich and the pile is incredibly dense. Kaaleen has a customer for life.",
    rating: 5,
    product: "Harf – Black Hand-Tufted",
  },
  {
    name: "Ananya Singh",
    location: "Delhi",
    text: "We ordered the Bronte for our daughter's room and it's perfect. Soft, easy to clean, and the colours haven't faded at all after six months of daily use.",
    rating: 5,
    product: "Bronte – Multicolor",
  },
  {
    name: "Vikram Nair",
    location: "Hyderabad",
    text: "Finally a brand that understands Indian taste but presents it in a modern way. The Harem carpet is stunning — every guest asks where we got it.",
    rating: 5,
    product: "Harem – Green Hand-Knotted",
  },
];
